# Reshaping Arrays

In [8]:
# changing a shape

import numpy as np

arr_s = np.arange(12).reshape(3,4)

print(arr_s)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [9]:
#convert to 1d list

arr_s.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [10]:
print(arr_s)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


Why hasn't our array changed? `reshape` returns a new array, `resize` changes the array ***in place***

In [17]:
arr = np.arange(8)
arr_r = arr.reshape(4,2)

print(arr)
print(arr_r)

[0 1 2 3 4 5 6 7]
[[0 1]
 [2 3]
 [4 5]
 [6 7]]


In [12]:
arr.resize(4,2)
print(arr)

[[0 1]
 [2 3]
 [4 5]
 [6 7]]


# Special Arrays

In [27]:
arr_0 = np.zeros((3,5)) #Why I have double paranthesis here?
print(arr_0)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [28]:
arr_0= np.zeros((2,2),dtype=bool)
arr_0

array([[False, False],
       [False, False]])

In [ ]:
arr_1= np.ones((2,3),dtype=int)
print(arr_1)

In [34]:
from numpy.random import *
rand(4,3)

import numpy as np

np.random.rand(4,3)

array([[0.2329852 , 0.43663435, 0.87564957],
       [0.87569803, 0.01630131, 0.81352504],
       [0.46679032, 0.3060893 , 0.26310372],
       [0.44708174, 0.71419394, 0.13953128]])

In [37]:
from numpy.random import *

int_from = -1
int_to = 17
randint(-1, 17, (4,3))


array([[ 2, 15,  7],
       [ 6, 13, -1],
       [ 7, 10,  4],
       [ 4, -1, 14]])