# Indexing

In [4]:
import numpy as np

arr=np.arange(10)
arr.resize(4,2)

arr

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [5]:
arr[0,0]

0

In [6]:
arr[0,:] # first row every element

array([0, 1])

In [10]:
a= arr[:,0] # first column every element

a

#a[0]

0

In [9]:
a= arr[:,:-1]  #first column - every element as a seperate array

a
#a[0]

array([0])

# Fancy indexing with Another Array

In [12]:
arr_i = np.array([[0,1],[0,1],[1,0],[1,0]], dtype=bool)
arr_i

array([[False,  True],
       [False,  True],
       [ True, False],
       [ True, False]])

In [14]:
arr[arr_i]=100 # replace with 100 where arr_i is True

arr

array([[  0, 100],
       [  2, 100],
       [100,   5],
       [100,   7]])

# Operations on Arrays

Mathematical operations performed elementwise. We can do addition, deleting, multiplication, and division on arrays. 

**Both arrays have to be of the same shape!**

# Addition

In [31]:
arr_b= arr+1
arr_b

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

In [32]:
arr+arr_b

array([[ 1.,  3.,  5.,  7.],
       [ 9., 11., 13., 15.],
       [17., 19., 21., 23.]])

# Multiplication

In [38]:
arr_c= arr*2
arr_c

array([[ 0.,  2.,  4.,  6.],
       [ 8., 10., 12., 14.],
       [16., 18., 20., 22.]])

In [40]:
arr_c*arr

array([[  0.,   2.,   8.,  18.],
       [ 32.,  50.,  72.,  98.],
       [128., 162., 200., 242.]])

# Subtraction

In [41]:
arr_c-arr_b

array([[-1.,  0.,  1.,  2.],
       [ 3.,  4.,  5.,  6.],
       [ 7.,  8.,  9., 10.]])

# Division

In [42]:
arr_c/arr_b

array([[0.        , 1.        , 1.33333333, 1.5       ],
       [1.6       , 1.66666667, 1.71428571, 1.75      ],
       [1.77777778, 1.8       , 1.81818182, 1.83333333]])

# Boolean

In [43]:
arr_c>20

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True]])